version: '3'

services:
  app:
    depends_on:
      - 'postgres'
    image: 'motoradmin/motoradmin:latest'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - .env 

  postgres:
    image: 'postgres:13.4'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - .env

volumes:
  postgres: 
